### ISSUE TITLE
GazeManager state pre-activation undocumented and unusable

### ISSUE THREAD

**Issue by ragset** [EyeTribe/tet-csharp-client#7]
I could not find any information in the official documentation ([Developers Guide](http://dev.theeyetribe.com/dev/), [API Reference](http://dev.theeyetribe.com/api/), [C#](http://dev.theeyetribe.com/csharp/)) on the value of `Trackerstate`, nor any other property of the GazeManager class, pre-activation. Unfortunately the ones I have tested all seem to be initialized to zero, which in the case of `Trackerstate` equates to `GazeManagerCore.TrackerState.TRACKER_CONNECTED`. As there are several ways to fix this (e.g. adding a `GazeManagerCore.TrackerState.UNDEFINED`, setting better initial values to the properties, documenting the issue, etc.) I figured an issue would be better than a pull-request for one of them.

Best regards
Ragnar

**Comment by arnebp** [comment]
Hi @ragset 

Thanks for your feedback. 

You are right. The [documentation](http://dev.theeyetribe.com/api/#tracker_state) of the TrackerState could be better and there needs to be a pre-activation state. That goes for all enum types in the GazeManager class. I'll look into this for the next release.

**Comment by ragset** [comment]
Perfect, thank you @arnebp !

**Comment by arnebp** [comment]
I took care of this in the latest release. Please verify fix and close issue @ragset :)

**Comment by ragset** [comment]
Thank you @arnebp !
